### ISSUE TITLE
xvfb-run errors without starting

### ISSUE THREAD

**Issue by ianstormtaylor** [captain401/heroku-buildpack-xvfb#1]
Hey @yoz,

I've noticed you posting in a few different places about getting Xvfb run working with Heroku, so I wanted to ask you a question... have you ever seen this error continually coming up:

```
-----> The github-netrc buildpack does not run tests. Skipping.
-----> The postgresql buildpack does not run tests. Skipping.
-----> The Apt buildpack does not run tests. Skipping.
-----> The Xvfb-setup buildpack does not run tests. Skipping.
-----> Running Node.js buildpack tests...
yarn test v0.23.2
$ make test 
DEBUG=nightmare*,electron* xvfb-run -e /dev/stdout -s "-screen 0 1280x1028x24 -ac +extension GLX +render" ./node_modules/.bin/mocha --timeout 60000 --bail --compilers js:babel-core/register --require babel-polyfill ./build/test/index.js
Xvfb: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
xvfb-run: error: Xvfb failed to start
Makefile:166: recipe for target 'test' failed
make: *** [test] Error 1
error Command failed with exit code 2.
-----> Node.js buildpack tests failed with exit status 1
```

Prior to this, I had many other similar errors...

```
<snip>
Fri, 19 May 2017 20:56:56 GMT electron:stderr /app/node_modules/electron/dist/electron: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory
<snip>
```
```
<snip>

Fri, 19 May 2017 20:45:31 GMT electron:stderr /app/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
<snip>
```

But all of those are after Nightmare has already started, and Electron runs into an issue. And they were fixed by simply adding more deps to the `Aptfile`.

This latest one seems to prevent `xvfb-run` from succeeding at all. And nothing I've tried has worked to get rid of it. Even if I remove previously-required things from `Aptfile` now and clear the cache, `xvfb-run` will still fail with the current error instead of the previous ones.

I'm really baffled, was hoping you could help. Thank you!

**Comment by ianstormtaylor** [comment]
Solved it, apparently I needed to install `electron` in my own `package.json` for some reason instead of relying on Nightmare brining it itself. Not sure why.

**Comment by yoz** [comment]
Hmm, that's strange, I haven't run across that error. I would run `heroku run dpkg -l` to see what packages are actually installed. I personally depend on a specific version of `electron-prebuilt` (I guess it's using `electron` now) to avoid unexpected breaking changes, which have bitten me in the past, but I don't know how that would help... I would also check your Heroku node modules cache and see if you get different results when you clear it.

**Comment by yoz** [comment]
Hi, I saw your comment here:

https://github.com/segmentio/nightmare/issues/497#issuecomment-303237550

I would believe that the missing libgl packages on heroku-16 are the root of your issue, and if you included them in your Aptfile as well, you'd have more success:

https://devcenter.heroku.com/articles/stack-packages
